const int s1 = 34; // PONEMOS CONSTANTE DEL PIN EN EL QUE ESTA CONECTADO EL OUTPUT DE NUESTRO PRIMER SENSOR
const int s2 = 35; // PONEMOS CONSTANTE DEL PIN EN EL QUE ESTA CONECTADO EL OUTPUT DE NUESTRO SEGUNDO SENSOR




void setup() {
  Serial.begin(9600); // INICIAMOS LA COMUNICACION CON ARDUINO A 9600 BAUDIOS
}

void loop() 
 {
  Serial.print(analogRead(s1)); // HACEMOS UN PRINT DE LO QUE LEEMOS ANALOGICAMENTE DEL SENSOR 1 (PIN34)
   Serial.print(",");
  Serial.println(analogRead(s2)); // HACEMOS UN PRINT DE LO QUE LEEMOS ANALOGICAMENTE DEL SENSOR 2 (PIN35)
  delay(100); // PONEMOS UN DELAY DE 100MS PARA NO LLENARNOS DE DATOS
}